"""Parameters for a run, loaded from YAML and validated once at the start.

Everything the pipeline does is set here. Nothing downstream reads a global or a
hard-coded constant, so a run is fully described by its config file plus the input
path. That is what makes a result reproducible, and it makes a new dataset a matter
of editing numbers rather than code.

Two parameters carry physical units and must be set for a new dataset. The rest have
defaults that were validated on 60 s spinning-disk recordings of Rab5-RFP endosomes in
glia at ~22 fps:

    dt_seconds    frame interval. Every rate, and the coarse-graining window, is in
                  seconds and converts through this.
    um_per_px     pixel size. Optional; leave null to work in pixels. When set,
                  distance columns are also reported in microns.

Load with `Config.load("config/default.yaml")`, or `Config.load(path, dt_seconds=0.05)`
to override individual fields from a notebook without editing the file.

YAML and JSON are interchangeable. JSON is a subset of YAML, so `.json` config files
load with no special handling, and `save()` writes whichever format the file extension
asks for. YAML is the default because it takes comments, and the comments in
config/default.yaml document the parameters. Use JSON when a config is generated by
another program rather than edited by a person.
"""
from __future__ import annotations

import copy
import dataclasses
import json
import math
import warnings
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml


@dataclass
class DriftConfig:
    enabled: bool = True
    smoothing_sigma: float = 6.0      # px; blur used to register on static content
    reference_frames: int = 20        # frames median-projected to form the reference
    median_filter: int = 5            # temporal smoothing of the shift series
    min_span_px: float = 0.5          # below this total drift, skip applying it


@dataclass
class DetectConfig:
    """deepBLINK, a convolutional network trained to find diffraction-limited spots.

    The network scores each frame on its own. For every 4x4-pixel cell it returns the
    probability that a spot centre lies there and the centre's sub-pixel offset; a
    cell above `prob_threshold` is a detection. See detect.py.
    """
    model: str = "vesicle"            # bundled deepBLINK model, or a path to a .h5 file
    prob_threshold: float = 0.5       # probability above which a grid cell is a spot
    batch_frames: int = 32            # frames per network call
    cache_dir: str | None = None      # keep probability maps here; null = recompute


@dataclass
class LinkConfig:
    search_range_px: float = 3.0      # max frame-to-frame displacement
    memory_frames: int = 15           # frames a spot may vanish and still be relinked
    min_length_frames: int = 40       # tracks with fewer detected frames are dropped
                                      #   before recovery and merging (see linking.py)
    merge_colocated_px: float = 4.0   # tracks whose mean positions are this close are
                                      #   one vesicle; 0 = off
    merge_gap_frames: int = 60        # fragment B may follow fragment A by this long...
    merge_gap_radius_px: float = 6.0  #   ...if it starts this close to where A ended
    merge_overlap_frames: int = 15    # fragments coexisting this long...
    merge_overlap_radius_px: float = 3.0  # ...this close together are one vesicle


@dataclass
class RecoverConfig:
    """Gap recovery: ask the network again, more leniently, where a track predicts a
    vesicle should be. See recover.py."""
    enabled: bool = True
    threshold: float = 0.1            # local probability threshold at the prediction
    radius_px: float = 2.0            # accept the closest peak within this distance
    search_cells: int = 1             # grid cells searched around the prediction
    max_extend_frames: int = 60       # how far past a track's ends to keep looking
    max_misses: int = 8               # stop extending after this many misses in a row


@dataclass
class SizeConfig:
    """Vesicle size from the intensity-weighted second moment.

    `psf_sigma_px` is the PSF width subtracted to give a size in excess of the
    diffraction limit. Leave it null to estimate it from the data as the
    `psf_from_percentile` percentile of measured widths; size.py explains why that
    is preferred over a theoretical value.
    """
    enabled: bool = True
    window_px: int = 4            # half-width; 4 -> a 9x9 window per spot
    psf_sigma_px: float | None = None   # null = calibrate from the data (see below)
    psf_from_percentile: float = 5.0    # when psf_sigma_px is null, take this
                                        #   percentile of measured widths as the PSF
    max_frames: int = 200         # frames sampled per track; sizing every frame of a
                                  #   1350-frame track is wasted precision


@dataclass
class MetricsConfig:
    tau_frames: int = 22              # coarse-graining window for run detection (~1 s)
    tau_directed_frames: int = 90     # timescale defining "consistent direction" (~4 s)
    max_turn_deg: float = 60.0        # a step turning more than this ends a run
    min_run_disp_px: float = 1.0      # runs shorter than this are not transport
    min_run_steps: int = 2            # a run must persist >= 2 coarse steps
    min_window_occupancy: float = 0.25  # fraction of tau a window must contain to
                                        #   count; see metrics.coarse
    n_permutations: int = 200         # per-vesicle null; 0 disables the p-value
    random_seed: int = 0


@dataclass
class ClassifyConfig:
    """Thresholds turning per-vesicle metrics into labels.

    With `use_permutation` (the default) a vesicle is a mover if its run metric beats
    its own direction-randomised null, rather than a fixed number. Set it false to
    use the rate threshold alone.
    """
    use_permutation: bool = True
    p_threshold: float = 0.05
    mover_rate_px_per_s: float = 0.15
    mover_min_net_px: float = 4.0
    exclude_max_step_px: float = 5.0   # single jump above this = suspected mislink
    exclude_n_big_steps: int = 5       # repeated wobble = suspected identity swap
    big_step_px: float = 3.0


@dataclass
class FiltersConfig:
    """Which vesicles count as usable. These add a label; no vesicle is deleted.

    Every vesicle is reported either way, with `passes_filter` and `filter_reason`,
    and the passing subset is written to a second file. `null` means the rule is off.
    """
    min_observed_frames: int | None = None  # frames actually detected; the hard floor
                                            #   link.min_length_frames already applies
    min_span_frames: int | None = None      # first-to-last extent; null = off
    require_directed_measurable: bool = True   # exact guarantee that `directed` exists
                                               #   for everything in the filtered set
    max_observed_frames: int | None = None
    min_lifetime_s: float | None = None     # on span (first to last sighting)
    max_lifetime_s: float | None = None     # see the selection-bias warning in filters.py
    min_frac_observed: float | None = 0.0   # reject tracks that are mostly gap
    max_longest_gap: int | None = None      # frames
    max_frac_recovered: float | None = None # reject tracks that are mostly recovered
    exclude_censored: bool = False          # tracks touching the first or last frame
    exclude_classes: list = field(default_factory=lambda: ["excluded"])
    rois: list = field(default_factory=list)    # empty = keep every region
    min_sigma_px: float | None = None
    max_sigma_px: float | None = None


@dataclass
class RenderConfig:
    three_panel: bool = True
    per_vesicle_images: bool = True
    per_vesicle_videos: bool = False   # off by default: one file per vesicle
    overview_video: bool = False
    max_vesicle_outputs: int = 25      # cap, so a dense cell cannot emit thousands
    trail_frames: int = 40
    frame_step: int = 4                # temporal downsample for videos
    fps: int = 20
    dpi: int = 150
    percentiles: list = field(default_factory=lambda: [1.0, 99.7])   # display stretch
    ffmpeg: str = "ffmpeg"


# Section name -> dataclass. The one place this mapping lives; loading, validation
# and the docs test all read it, so a new section cannot be added to one and missed
# by the others.
SECTIONS = {"drift": DriftConfig, "detect": DetectConfig, "link": LinkConfig,
            "recover": RecoverConfig, "size": SizeConfig, "metrics": MetricsConfig,
            "classify": ClassifyConfig, "filters": FiltersConfig, "render": RenderConfig}


@dataclass
class Config:
    dt_seconds: float = 0.0446
    um_per_px: float | None = None
    output_dir: str = "output"
    drift: DriftConfig = field(default_factory=DriftConfig)
    detect: DetectConfig = field(default_factory=DetectConfig)
    link: LinkConfig = field(default_factory=LinkConfig)
    recover: RecoverConfig = field(default_factory=RecoverConfig)
    size: SizeConfig = field(default_factory=SizeConfig)
    metrics: MetricsConfig = field(default_factory=MetricsConfig)
    classify: ClassifyConfig = field(default_factory=ClassifyConfig)
    filters: FiltersConfig = field(default_factory=FiltersConfig)
    render: RenderConfig = field(default_factory=RenderConfig)

    # ---------------------------------------------------------------- loading
    @classmethod
    def load(cls, path: str | Path | None = None, **overrides: Any) -> "Config":
        raw: dict = {}
        if path is not None:
            # safe_load handles JSON too - JSON is a subset of YAML - so .json and
            # .yaml config files are equally acceptable with no branch here.
            raw = yaml.safe_load(Path(path).read_text()) or {}
            if not isinstance(raw, dict):
                raise ValueError(
                    f"{path} does not contain a mapping of settings "
                    f"(parsed as {type(raw).__name__})")
        cfg = cls._from_dict(raw)
        for k, v in overrides.items():
            cfg.set(k, v)
        cfg.validate()
        return cfg

    @classmethod
    def _from_dict(cls, raw: dict) -> "Config":
        known_keys = {f.name for f in dataclasses.fields(cls)}
        kwargs: dict = {}
        for key, val in raw.items():
            if key not in known_keys:
                raise ValueError(
                    f"unknown config key {key!r}. Known keys: {sorted(known_keys)}")
            sub = SECTIONS.get(key)
            if sub is None:
                kwargs[key] = val
            else:
                if not isinstance(val, dict) and val is not None:
                    raise ValueError(
                        f"config section {key!r} must be a mapping of settings, got "
                        f"{type(val).__name__}: {val!r}. To turn a stage off use its "
                        f"own flag, e.g. `{key}:\n  enabled: false`.")
                known = {f.name for f in dataclasses.fields(sub)}
                bad = set(val or {}) - known
                if bad:
                    raise ValueError(f"unknown key(s) {sorted(bad)} under {key!r}. "
                                     f"Known: {sorted(known)}")
                kwargs[key] = sub(**(val or {}))
        return cls(**kwargs)

    def set(self, dotted: str, value: Any) -> None:
        """cfg.set("detect.prob_threshold", 0.4) - for notebook overrides."""
        obj = self
        parts = dotted.split(".")
        for p in parts[:-1]:
            obj = getattr(obj, p)
        if not hasattr(obj, parts[-1]):
            raise ValueError(f"unknown config field {dotted!r}")
        setattr(obj, parts[-1], value)

    def copy(self, **overrides: Any) -> "Config":
        cfg = copy.deepcopy(self)
        for k, v in overrides.items():
            cfg.set(k, v)
        cfg.validate()
        return cfg

    def to_dict(self) -> dict:
        return dataclasses.asdict(self)

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)

    def to_yaml(self) -> str:
        return yaml.safe_dump(self.to_dict(), sort_keys=False)

    def save(self, path: str | Path) -> None:
        """Write the config out. Format follows the extension: .json gets JSON,
        anything else gets YAML.

        Called automatically next to every result, so a figure can always be traced
        back to the parameters that produced it.
        """
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        text = self.to_json() if path.suffix.lower() == ".json" else self.to_yaml()
        path.write_text(text)

    # ------------------------------------------------------------- validation
    def validate(self) -> None:
        # Types first. A NaN passes every inequality below (all comparisons with NaN
        # are False), and a numpy scalar would survive the whole run and then break
        # yaml.safe_dump at save time.
        for name, val in (("dt_seconds", self.dt_seconds),
                          ("um_per_px", self.um_per_px)):
            if val is None:
                continue
            if not isinstance(val, (int, float)) or isinstance(val, bool):
                raise ValueError(f"{name} must be a plain number, got "
                                 f"{type(val).__name__}: {val!r}")
            if math.isnan(val) or math.isinf(val):
                raise ValueError(f"{name} must be finite, got {val!r}")
        if self.dt_seconds is None:
            raise ValueError("dt_seconds is required and must be > 0")
        if self.dt_seconds <= 0:
            raise ValueError("dt_seconds must be > 0")
        for name, val in (("metrics.tau_frames", self.metrics.tau_frames),
                          ("metrics.tau_directed_frames",
                           self.metrics.tau_directed_frames)):
            if not isinstance(val, int) or val < 1:
                raise ValueError(f"{name} must be an integer >= 1, got {val!r}. "
                                 "0 collapses every track to one window and makes "
                                 "`directed` undefined.")
        if self.drift.reference_frames < 1:
            raise ValueError(
                f"drift.reference_frames must be >= 1, got "
                f"{self.drift.reference_frames}. 0 silently disables drift "
                "correction and a negative value means 'all but the last N', "
                "neither of which is ever intended.")
        if not 0 < self.detect.prob_threshold < 1:
            raise ValueError("detect.prob_threshold must be in (0, 1): it is a "
                             "probability")
        if self.detect.batch_frames < 1:
            raise ValueError("detect.batch_frames must be >= 1")
        if self.link.search_range_px <= 0:
            raise ValueError("link.search_range_px must be > 0")
        if self.link.memory_frames < 0:
            raise ValueError("link.memory_frames must be >= 0")
        if self.link.min_length_frames < 3:
            raise ValueError("link.min_length_frames must be >= 3: a two-frame track "
                             "has a single step and no measurable motion")
        if self.recover.enabled:
            if not 0 < self.recover.threshold < self.detect.prob_threshold:
                raise ValueError(
                    f"recover.threshold={self.recover.threshold} must lie between 0 and "
                    f"detect.prob_threshold={self.detect.prob_threshold}: recovery "
                    "accepts weaker responses than detection, so a threshold at or "
                    "above the detection threshold can never recover anything")
            if self.recover.radius_px <= 0 or self.recover.search_cells < 0:
                raise ValueError("recover.radius_px must be > 0 and "
                                 "recover.search_cells >= 0")
        # The permutation p-value cannot go below 1/(n+1). A threshold under that
        # floor makes `mover` unreachable for every vesicle, with no error.
        floor = 1.0 / (self.metrics.n_permutations + 1)
        if (self.classify.use_permutation
                and self.classify.p_threshold < floor):
            raise ValueError(
                f"classify.p_threshold={self.classify.p_threshold} is below the "
                f"permutation floor 1/(n_permutations+1)={floor:.4f}, so no vesicle "
                f"can ever be classified a mover. Raise the threshold or raise "
                f"metrics.n_permutations to at least "
                f"{int(round(1 / self.classify.p_threshold)) - 1}.")
        if self.um_per_px is not None and self.um_per_px <= 0:
            raise ValueError("um_per_px must be > 0 or null")
        if self.metrics.tau_directed_frames < self.metrics.tau_frames:
            raise ValueError("tau_directed_frames should be >= tau_frames: the "
                             "directed path is measured at the coarser timescale")
        if self.metrics.min_run_steps < 2:
            raise ValueError(
                "min_run_steps < 2 lets a single step count as a directed run, which "
                "collapses the directed metric onto plain path length and destroys "
                "its contrast against the null")
        if not 0 < self.classify.p_threshold < 1:
            raise ValueError("classify.p_threshold must be in (0, 1)")
        # `directed` needs at least two tau-windows, which is a requirement on span
        # (first to last sighting), not on the number of frames detected. Real
        # vesicles are only ~40% observed, so a track spanning 400 frames holds ~163
        # detections; a gate of 2*tau = 180 on observed frames would reject the
        # genuine vesicles.
        if not 0.0 <= self.metrics.min_window_occupancy <= 1.0:
            raise ValueError("metrics.min_window_occupancy must be in [0, 1]")
        need = 2 * self.metrics.tau_directed_frames
        span = self.filters.min_span_frames
        if span is not None and span < need:
            warnings.warn(
                f"filters.min_span_frames={span} is below "
                f"2*metrics.tau_directed_frames={need}: tracks spanning less than "
                f"{need} frames cannot have a `directed` value at this timescale, so "
                f"part of the FILTERED set will report NaN there. Set "
                f"min_span_frames={need} to keep the filtered set coherent, or accept "
                f"that `directed` is defined for only part of it.", stacklevel=2)
        if self.classify.use_permutation and self.metrics.n_permutations < 20:
            raise ValueError("classify.use_permutation needs metrics.n_permutations "
                             ">= 20 to give a usable p-value")

    # ----------------------------------------------------------------- units
    @property
    def tau_seconds(self) -> float:
        return self.metrics.tau_frames * self.dt_seconds

    @property
    def tau_directed_seconds(self) -> float:
        return self.metrics.tau_directed_frames * self.dt_seconds
